//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Wave_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyShare
    {
        public int buy_id { get; set; }
        public Nullable<int> n_shares { get; set; }
        public Nullable<int> share_id { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> business_id { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Share Share { get; set; }
        public virtual User User { get; set; }
    }
}
