//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Wave_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BuyShares = new HashSet<BuyShare>();
            this.SellShares = new HashSet<SellShare>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public Nullable<int> role_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> user_addr { get; set; }
        public string phone_no { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> remember_me { get; set; }
        public Nullable<decimal> account_bal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyShare> BuyShares { get; set; }
        public virtual Region Region { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellShare> SellShares { get; set; }
    }
}
